### ISSUE TITLE
License on code and ASCII art?

### ISSUE THREAD

**Issue by phantom-voltage** [janbrennen/rice#3]
Hey, love your scripts. I run an SSH server for roguelikes, and thought the skull ASCII art would make a great greeting for players. I was wondering if you drew this yourself and if I could get permission to use it.

**Comment by Chuuni** [comment]
@janbrennen said it's not theirs and can't say what you can and can't do with it.

**Comment by f41c0r** [comment]
the readme makes it sound like janbrennen wrote hack.exe.c

**Comment by JohnDDuncanIII** [comment]
The skull ascii art in Hal's '3spooky' script was taken from [Skinwalker's issue file](https://github.com/DaisukeAramaki/Dotfiles/blob/master/issue), which I modified ages ago to link to [lazy's blog](https://sites.google.com/site/lazyboxx/---home) and popularized by spamming it in my screenshots. That skull art itself is taken from the card game [`Magic: The Gathering'](http://www.artfire.com/uploads/product/7/267/82267/6082267/6082267/large/mtg_magic_mana_symbol_black_swamps_-_4_x_4_decals_76593209.jpg) iirc. I can't say the same for the ascii art from hack.exe, whose creator I can't say I know. I was the one who ported pipes.sh to work on OS X years ago I believe. The rest is history. Most of these silly scripts were popularized by a few on the imageboard years ago and eventually creeped out to various users github accounts.
